Draft: Model Hand Landmark.
tenstorrent/pytorch2.0_ttnn pull request #140
Opened 2024-09-01 02:51 UTC by cthsieh

### Ticket
None

### Problem description
Add model Hand Landmark to trace.

This test depends on fixture manage_depedencies which was developed in PR 137. So, review PR 137 first, and then I continue to finish this PR in case of any change according to PR 137.

### What's changed
Add model Hand Landmark.

2024-09-04 00:02 UTC, ayerofieiev-tt approved these changes

2024-09-04 00:03 UTC, ayerofieiev-tt requested changes
Did not spot the 8MB file in the repo.

2024-09-04 00:03 UTC, ayerofieiev-tt commented
Need to decide what to do with a file and whether we have to enable git lfs.

2024-09-09 08:16 UTC, cthsieh commented
> Need to decide what to do with a file and whether we have to enable git lfs.

I chosen git lfs since it's a common way to handle such a problem. I closed this PR and opened another PR #171.

2024-09-09 08:16 UTC, closed without merging